// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qakzboejxxegpodkffgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFha3pib2VqeHhlZ3BvZGtmZmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEzNjMwNzcsImV4cCI6MjEwNjkzOTA3N30.MQfjhvy9NeBGW3ePWLM4xqeNDyP_bJRjWi0EQG4tV1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});